api: add HTTP-like object uploader
nspcc-dev/neofs-rest-gw pull request #124
Opened 2023-12-22 15:46 UTC by tatiana-nspcc

Add `POST /upload/{cid}` API.

Close https://github.com/nspcc-dev/neofs-rest-gw/issues/111.

2023-12-22 16:11 UTC, tatiana-nspcc commented
I receive an error while trying to use custom multipart reader:
```
2023-12-22T16:06:27.370Z        error   handlers/api.go:206     could not receive multipart/form        {"error": "multipart: NextPart: EOF"}
```
It's line https://github.com/nspcc-dev/neofs-rest-gw/blob/312cb7dd19203dfa2227717c0d924b7f89350f13/handlers/multipart/multipart.go#L343

2023-12-25 09:49 UTC, cthulhu-rider commented
> I receive an error while trying to use custom multipart reader:

@tatiana-nspcc 

u dont need this manual multipart decoder https://github.com/nspcc-dev/neofs-rest-gw/pull/124#issuecomment-1867856599

try this:
```go
	if swagFile, ok := params.File.(*swag.File); ok {
		header = swagFile.Header
		file = swagFile.Data
	} else {
		const fileKey = "file"
		file, header, err = params.HTTPRequest.FormFile(fileKey)
		if err != nil {
			resp := a.logAndGetErrorResponse(fmt.Sprintf("get file %q from HTTP request", fileKey), err)
			return errorResponse.WithPayload(resp)
		}
	}
```

2023-12-27 11:44 UTC, tatiana-nspcc commented
Thanks, @cthulhu-rider I've used that.

When I tried to run the test cases, I noticed that http-gw doesn't care about the naming of the field for upload. In the examples (https://github.com/nspcc-dev/neofs-http-gw/blob/0b22557622db8551bfbfc8d0ff0fde51fbdea9c3/README.md#L538), I see the `file` field, but the test cases use the `upload_file` field name and sometimes `file`. However, any arbitrary name can be used for the field. For the rest-gw, we should choose a fixed name for the file field, I think. Which one should we choose?

2023-12-28 17:51 UTC, cthulhu-rider commented
> Which one should we choose?

definitely strict behavior. There may be several files in any request. API server must clearly distinguish them on the server and require strict compliance with the protocol for system stability.

> However, any arbitrary name can be used for the field.

it's an incorrect behavior to me that will break if we add one more file into the request. Lucky we dont care bout HTTP GW anymore

> For the rest-gw, we should choose a fixed name for the file field

`payload`. And we must double-check that server responds with 4XX (in practice `400 Bad Request`, but most important that not 2XX) if we set any other name like `file`

2024-01-15 08:59 UTC, smallhive commented on handlers/objects.go
> +		//ok       bool
Looks like unused, it is better to remove

2024-01-17 08:55 UTC, cthulhu-rider commented on spec/rest.yaml
> +  AddressForUpload:
is this redundant while having https://github.com/nspcc-dev/neofs-rest-gw/blob/eee70710319474482244e479bfb0bfe6f1b68b14/spec/rest.yaml#L994-L1007?

2024-01-17 09:22 UTC, tatiana-nspcc commented on spec/rest.yaml
> +  AddressForUpload:
No, while we are keeping the rest-gw in a working state and want to pass tests for http-gw. This is because the tests require `object_id` and `container_id`, but we've had `containerId` and `objectId`.

2024-01-17 12:43 UTC, roman-khimov requested changes

2024-01-17 12:43 UTC, roman-khimov commented on handlers/objects.go
> +		file, header, err = params.HTTPRequest.FormFile(fileKey)
This will break third-party code for sure. We need to replicate the old behavior (one file only, careless wrt name (except for empty one)) exactly here. We can then have different API endpoint with some "better" behavior, but I doubt it'd be useful.

2024-01-17 12:43 UTC, roman-khimov commented on handlers/util.go
> +var neofsAttributeHeaderPrefixes = [...][]byte{[]byte("Neofs-"), []byte("NEOFS-"), []byte("neofs-")}
IIRC default `net/http` canonicalizes header names, so just `Neofs-` should be sufficient (please check though). See https://pkg.go.dev/net/http#Header

2024-01-17 12:43 UTC, roman-khimov commented on handlers/util.go
> +		value := strings.Join(values, ", ")
This doesn't seem right and it differs from the HTTP gw behavior. You can have multiple headers of the same name, but HTTP gw would just choose the latest one, concatenation would lead to a different result.

2024-01-17 12:43 UTC, roman-khimov commented on handlers/util.go
> +		if len(keyBytes) == 0 || len(valueBytes) == 0 {
This check is also better be done first.

2024-01-18 21:25 UTC, tatiana-nspcc commented on handlers/objects.go
> +		file, header, err = params.HTTPRequest.FormFile(fileKey)
I'm keeping the payload field for the proper behaviour (off-topic: what was the purpose of creating a service with no fixed field name?...). But if there's no file there, it will look for a file in any other field, just not in an empty one.

2024-01-18 21:26 UTC, tatiana-nspcc commented on handlers/util.go
> +var neofsAttributeHeaderPrefixes = [...][]byte{[]byte("Neofs-"), []byte("NEOFS-"), []byte("neofs-")}
Yes, checked, fixed.

2024-01-18 21:29 UTC, tatiana-nspcc commented on handlers/util.go
> +		value := strings.Join(values, ", ")
Actually, you cannot have multiple headers with the same name, because the http-gw will return an error: "key duplication error". So, I've modified the code to behave in the same way.

2024-01-18 21:32 UTC, tatiana-nspcc commented on handlers/util.go
> +		if len(keyBytes) == 0 || len(valueBytes) == 0 {
What do you mean? I've modified this part a little bit, but check it as soon as it's possible.

2024-01-19 08:44 UTC, roman-khimov commented on handlers/objects.go
> +		file, header, err = params.HTTPRequest.FormFile(fileKey)
Should be compatible the way it's now. HTTP gw implementation was like "whatever works for a single file upload".

2024-01-19 08:49 UTC, roman-khimov commented on handlers/util.go
> +var neofsAttributeHeaderPrefix = []byte("Neofs-")
I think you can make it a string `const` now...

2024-01-19 08:49 UTC, roman-khimov commented on handlers/util.go
> +		keyBytes := []byte(key)
And then avoid this conversion here as well.

2024-01-19 08:49 UTC, roman-khimov commented on handlers/util.go
> +		k, v := string(clearKey), string(valueBytes)
Because in the end of the day you need some `string`s anyway.

2024-01-19 08:49 UTC, roman-khimov commented on handlers/util.go
> +		valueBytes := []byte(values[0])
And this one.

2024-01-19 14:39 UTC, tatiana-nspcc commented on handlers/util.go
> +var neofsAttributeHeaderPrefix = []byte("Neofs-")
Thanks, fixed.

2024-01-19 14:39 UTC, tatiana-nspcc commented on handlers/util.go
> +		keyBytes := []byte(key)
Removed.

2024-01-19 14:41 UTC, tatiana-nspcc commented on handlers/util.go
> +		k, v := string(clearKey), string(valueBytes)
Yes, I've changed all the bytes references to the strings package.

2024-01-19 14:41 UTC, tatiana-nspcc commented on handlers/util.go
> +		valueBytes := []byte(values[0])
Fixed.

2024-01-19 15:04 UTC, roman-khimov approved these changes

2024-01-19 15:05 UTC, merged