*: Add GET and OPTIONS requests for `network_info`
nspcc-dev/neofs-rest-gw pull request #202
Opened 2024-04-22 13:49 UTC by tatiana-nspcc

It returns current network settings such as: `audit_fee`, `container_fee`, `epoch_duration`, `homomorphic_hashing_disabled`, `ir_candidate_fee`, `maintenance_mode_allowed`, `max_object_size`, `named_container_fee`, `storage_price`, `withdrawal_fee`.

Close #198.

2024-04-23 11:22 UTC, smallhive approved these changes

2024-04-24 10:02 UTC, roman-khimov requested changes

2024-04-24 10:02 UTC, roman-khimov commented on spec/rest.yaml
> +  /network_info:
https://stackoverflow.com/questions/10302179/hyphen-underscore-or-camelcase-as-word-delimiter-in-uris

I know we inherited `get_by_attribute` and we only have single word APIs otherwise, but let's do it better here.

2024-04-24 22:40 UTC, tatiana-nspcc commented on spec/rest.yaml
> +        - storage_price
Good point, but I was inspired by the most common used response:
```
{
  "object_id": "8N3o7Dtr6T1xteCt6eRwhpmJ7JhME58Hyu1dvaswuTDd",
  "container_id": "5HZTn5qkRnmgSz9gSrw22CEdPPk6nQhkwf2Mgzyvkikv"
}
```
Should we change it here too? If yes, I prefer a separate issue.

2024-04-24 22:54 UTC, tatiana-nspcc commented on spec/rest.yaml
> +  /network_info:
I've changed it to ` /network-info`

2024-04-24 22:55 UTC, tatiana-nspcc commented on spec/rest.yaml
> +        ir_candidate_fee:
Fixed.

2024-04-24 22:56 UTC, tatiana-nspcc commented on spec/rest.yaml
> +        - storage_price
I've changed them to camelCase.

2024-04-24 22:56 UTC, tatiana-nspcc commented on spec/rest.yaml
> +        maintenance_mode_allowed:
Fixed.

2024-04-24 22:56 UTC, tatiana-nspcc commented on spec/rest.yaml
> +          description: Network information in NeoFS.
"from". Thank you.

2024-04-24 22:56 UTC, tatiana-nspcc commented on spec/rest.yaml
> +        - storage_price
I've changed them to camelCase.

2024-04-25 07:37 UTC, roman-khimov commented on spec/rest.yaml
> +        - storage_price
> Should we change it here too?

No. This was inherited from HTTP obviously, but that's exactly the thing we can fix in #168 which is a new API. Old one can't be changed.

2024-04-25 07:38 UTC, roman-khimov approved these changes

2024-04-25 07:38 UTC, merged