Add support for `Range` header in object GET requests
nspcc-dev/neofs-rest-gw pull request #241
Opened 2024-08-22 21:18 UTC by tatiana-nspcc

The `Range` header is now accepted for `/objects/{cid}/by_id/{oid}` and `/objects/{cid}/by_attribute/{oid}` requests.
    
Close #224.

2024-08-23 04:43 UTC, smallhive commented on handlers/newObjects.go
> +	}
I understand it shortens the code, but I would separate these errors with a custom text description. It will help to identify what exactly the problem is

2024-08-23 04:43 UTC, smallhive commented on handlers/newObjects.go
> +		return 0, 0, errors.New("wrong Range header format")
errors.New("bytes= prefix required")

2024-08-23 04:43 UTC, smallhive commented on handlers/rangeReader.go
> +		if err != nil && err != io.EOF {
`err != io.EOF` -> `!errors.Is(err, io.EOF)` ?
the same below

2024-08-23 04:43 UTC, smallhive commented on spec/rest.yaml
> +        example: "bytes=500-999"
Do we need `bytes=` part inside the header value? Could we use only the numbers range?

The header already contains a separate value and doesn't require an extra prefix. Except situation we a planning to use different prefixes in the future

2024-08-23 07:17 UTC, tatiana-nspcc commented on spec/rest.yaml
> +        example: "bytes=500-999"
As far as I know, this format is standard. And it always begins with description of units for Range. `neofs-s3-gw` supports it in the same way.

2024-08-23 08:03 UTC, smallhive commented on spec/rest.yaml
> +        example: "bytes=500-999"
Ok

2024-08-23 08:17 UTC, tatiana-nspcc commented on handlers/newObjects.go
> +		return 0, 0, errors.New("wrong Range header format")
Fixed.

2024-08-23 08:17 UTC, tatiana-nspcc commented on handlers/rangeReader.go
> +		if err != nil && err != io.EOF {
Fixed.

2024-08-23 08:25 UTC, tatiana-nspcc commented on handlers/newObjects.go
> +	}
I don't think it will be useful here. Usually, browsers request to send a part of the downloading file, and there won't be any errors. But if a human sends this request manually, it is just a string like `bytes=100-200`, and it's not so complicated to find an error. However, I can do that if you insist.

2024-08-23 08:31 UTC, smallhive commented on handlers/newObjects.go
> +	}
Let it be as is. It can be easily changed later

2024-08-23 08:32 UTC, smallhive approved these changes

2024-08-23 08:45 UTC, roman-khimov requested changes
Please also add `Accept-Ranges`

2024-08-23 08:45 UTC, roman-khimov commented on handlers/newObjects.go
> +	// Read the object header to determine the size of the payload.
I think it's even more important for attributes. Size is not needed if you know the range exactly (500-999), but attributes can't be properly set without a header.

2024-08-23 08:45 UTC, roman-khimov commented on handlers/newObjects.go
> +	if !strings.HasPrefix(rangeParam, prefix) {
You can simplify `HasPrefix/TrimPrefix` with `CutPrefix` (https://pkg.go.dev/strings#CutPrefix).

2024-08-23 08:45 UTC, roman-khimov commented on handlers/newObjects.go
> +	arr := strings.Split(strings.TrimPrefix(rangeParam, prefix), "-")
It's not that easy, you can have multipart range request (https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests#multipart_ranges).

2024-08-23 08:45 UTC, roman-khimov commented on handlers/newObjects.go
> +	arr := strings.Split(strings.TrimPrefix(rangeParam, prefix), "-")
But I doubt it's often used, so you can detect it and throw an "unsupported multipart range request" for now and create an issue for the future.

2024-08-23 08:45 UTC, roman-khimov commented on handlers/newObjects.go
> +		offset = 0
Too much. Imagine 1GB offset in request. You only need the first ~1K IIRC(or `sizeToDetectType` exactly) to detect the content type, so you can issue a separate range request to fetch it if needed (if the real requested offset is more than 4K, otherwise fetching and skipping some first bytes is faster).

2024-08-23 12:22 UTC, tatiana-nspcc commented on handlers/newObjects.go
> +	// Read the object header to determine the size of the payload.
Fixed the comment, but the size is important for the logic of calculating range, as "bytes=1000-" and "bytes=-1000" are valid parameters.

2024-08-23 12:22 UTC, tatiana-nspcc commented on handlers/newObjects.go
> +	if !strings.HasPrefix(rangeParam, prefix) {
Fixed.

2024-08-23 12:23 UTC, tatiana-nspcc commented on handlers/newObjects.go
> +	arr := strings.Split(strings.TrimPrefix(rangeParam, prefix), "-")
I've created https://github.com/nspcc-dev/neofs-rest-gw/issues/242

2024-08-23 12:23 UTC, tatiana-nspcc commented on handlers/newObjects.go
> +	base, bitSize := 10, 64
Fixed.

2024-08-23 13:17 UTC, roman-khimov commented on handlers/newObjects.go
> +		offset = 0
It doesn't matter what you do during upload via REST, objects can be uploaded in many many ways. So there is an object already in NeoFS that doesn't have any Content-Type. What are the options then?

2024-08-23 13:18 UTC, roman-khimov commented on handlers/newObjects.go
> +	// Read the object header to determine the size of the payload.
That's exactly what I wrote above.

2024-08-23 17:59 UTC, tatiana-nspcc commented on handlers/newObjects.go
> +		offset = 0
Okay, added constant `const maxRangeStart = 4096` and suitable logic.

2024-08-26 21:01 UTC, roman-khimov reviewed
Accept-Ranges?

2024-08-27 09:21 UTC, tatiana-nspcc commented
> Accept-Ranges?

Sorry, added.

2024-08-27 12:09 UTC, roman-khimov approved these changes

2024-08-27 12:09 UTC, merged